export default[
    {
      path:"/",
      name:"Layout",
      component:()=>import("../views/LayOut.vue"),
      redirect:"/index",
      children:[
        {
          path:"/index",
          name:"index",
         component:()=>import("../views/index/HomeIndex.vue")
        },
        {
          path:"/orders/list",
          name:"orders_list",
          component:()=>import("../views/orders/OrdersList")
        },
      ]
    },
    {
      path:"/login",
      name:"Login",
      component:()=>import("../views/LoginVue.vue")
     
    },{
      path:"*",
      name:"NotFound",
      component:()=>import("@/views/NotFound.vue")
    }
  ]